seed_everything: 27
trainer:
#  logger:
#    - class_path: pytorch_lightning.loggers.WandbLogger
#      init_args:
#        name: first-try
#        project: brain-classification
#        log_model: True
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 15
        min_delta: 0.0
        verbose: true
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
  default_root_dir: logs
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: [0]
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: null
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  train_dataset_path: /media/vadbeg/HDD/Data_HDD/Kaggle/BraTS2021_seg/BraTS2021_Training_Data
  labels_path: /home/vadbeg/Data_SSD/Kaggle/rsna-miccai-brain-tumor-radiogenomic-classification/train_labels.csv
  train_split_percent: 0.7
  dataset_item_limit: null
  shuffle_dataset: true
  ct_file_extension: '**/*_seg.nii.gz'
  index_position_in_name: 1
  original_clip_min: 0
  original_clip_max: 4
  batch_size: 3
  num_processes: 1
  spatial_size:
    - 196
    - 196
    - 128
  learning_rate: 0.001
  model_depth: 10
  num_input_channels: 1
  num_classes: 2
